module.exports = {
  loginScreenConstants: {
    title: 'Welcome to RNContaxts',
    subTitle: 'Please login here',
    userName: 'Username',
    userNamePlaceHolder: 'Enter username',
    password: 'Password',
    passwordPlaceHolder: 'Enter password',
    show: 'Show',
    hide: 'Hide',
    login: 'Login',
    needNewAccount: 'Need a new account?',
    signUp: 'Sign up',
  },
  signupScreenConstants: {
    title: 'Welcome to RNContaxts',
    subTitle: 'Create a free account',
    userName: 'Username',
    userNamePlaceHolder: 'Enter username',
    firstName: 'First Name',
    firstNamePlaceHolder: 'Enter First name',
    lastName: 'Last Name',
    lastNamePlaceHolder: 'Enter Last name',
    email: 'Email',
    emailPlaceHolder: 'Enter Email',
    password: 'Password',
    passwordPlaceHolder: 'Enter password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceHolder: 'Enter password again',
    signUp: 'Sign up',
    alreadyHaveAccount: 'Already have an account?',
    login: 'Login',
    show: 'Show',
    hide: 'Hide'
  },
};
